from Proj.module import *

"""
library = Library("Shin Bet",6,75,2)
book = Book("the red lotus","van dam",1974,5,5,5)
book2 = Book("the red lotus2","van dam",1974,5,5,5)
book3 = Book("the red lotus","van dam",1974,5,5,5)
print(library.DictOfNumOfBooks)
print(library.ListOfBooks)
library.addBook(book)
library.addBook(book2)
library.addBook(book3)
print(library.DictOfNumOfBooks)
print(library.ListOfBooks)
print(library.printListOfBooks())
"""
library = Library("Shin Bet",6,75,2)
c = Client()
c1 = Client()
c1.printClientInfo()
library.addClient(c)
library.addClient(c1)
print(library.listOfClients)
c.printClientInfo()
print(library.listOfClients[0].listOfLibrariesRegisteredTo[0].name)